"""Generate the SAMPLE dataset.

Read this before you read the numbers
-------------------------------------
The CSVs in this directory are **synthetic sample data**, generated by this
script from a fixed seed. They are not measurements of a real process.

They exist so the analysis is runnable and reviewable end to end -- so you can
see the method, argue with it, and check that the arithmetic in the README
comes out of the data rather than out of the air.

``data/README.md`` explains how to collect the real thing and drop it in.
Nothing else changes: the same script produces the same report from real rows.

The generator is deliberately not flattering to the automation:

* the manual arm improves slightly over time, because people get faster at a
  repetitive task, and ignoring that would credit the automation with a
  learning curve that was already happening;
* the automated arm keeps a non-zero error rate and a long tail, because
  automation moves failures rather than abolishing them;
* two automated runs fail outright and are recorded as the full manual cost
  plus rework, because a fallback to the manual process is part of the
  automated arm's real cost.

Regenerate:  py data/_generate_sample_data.py
"""

from __future__ import annotations

import csv
import pathlib
import random

HERE = pathlib.Path(__file__).resolve().parent

# Fixed seed: the README's numbers must be reproducible by anyone who runs
# this, or the whole point of the project is lost.
SEED = 20260921

HEADER = ["date", "batch_size", "minutes", "errors", "rework_minutes", "note"]


def weekdays(start_year: int, start_month: int, start_day: int, count: int):
    import datetime as dt

    day = dt.date(start_year, start_month, start_day)
    produced = 0
    while produced < count:
        if day.weekday() < 5:
            yield day.isoformat()
            produced += 1
        day += dt.timedelta(days=1)


def manual(rng: random.Random) -> list[list]:
    """12 weeks of the manual process, 5 days a week."""
    rows = []
    for index, date in enumerate(weekdays(2026, 1, 5, 60)):
        batch = rng.randint(28, 61)

        # ~1.9 min/invoice, drifting down ~12% over the period: people get
        # faster at a repetitive task. Crediting that to the automation would
        # be taking credit for a learning curve already in progress.
        base = 1.92 * (1 - 0.12 * index / 59)
        minutes = round(batch * base * rng.uniform(0.88, 1.15), 1)

        # Manual transcription errors: roughly 1 in 55 invoices.
        errors = sum(1 for _ in range(batch) if rng.random() < 0.018)
        rework = round(errors * rng.uniform(6.0, 14.0), 1)

        note = ""
        if rng.random() < 0.08:
            # Month-end spikes. These are what the p95 is measuring, and they
            # are the part of the manual process that actually hurt.
            minutes = round(minutes * rng.uniform(1.4, 1.9), 1)
            note = "month-end volume"

        rows.append([date, batch, minutes, errors, rework, note])
    return rows


def automated(rng: random.Random) -> list[list]:
    """12 weeks after the cutover, same cadence."""
    rows = []
    for index, date in enumerate(weekdays(2026, 4, 6, 60)):
        batch = rng.randint(31, 66)  # volume grew slightly

        # The human is now reviewing exceptions and approving, not typing.
        minutes = round(batch * 0.24 * rng.uniform(0.8, 1.35) + rng.uniform(1.5, 4.0), 1)

        # Errors do not go to zero. They change shape: a malformed PDF the
        # parser reads wrong, a supplier who changed their invoice layout.
        errors = sum(1 for _ in range(batch) if rng.random() < 0.0035)
        rework = round(errors * rng.uniform(4.0, 11.0), 1)

        note = ""
        if index in (17, 44):
            # A genuine automation failure, fallen back to the manual process.
            # Recording it at full manual cost is the honest accounting: a
            # fallback is part of what the automated arm costs.
            minutes = round(batch * 1.8 * rng.uniform(0.95, 1.1) + 12, 1)
            errors += 1
            rework = round(rework + 18.0, 1)
            note = "parser failure, processed manually"
        elif rng.random() < 0.05:
            minutes = round(minutes * rng.uniform(1.3, 1.7), 1)
            note = "batch of exceptions to review"

        rows.append([date, batch, minutes, errors, rework, note])
    return rows


def write(path: pathlib.Path, rows: list[list]) -> None:
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.writer(handle)
        writer.writerow(HEADER)
        writer.writerows(rows)
    print("wrote " + path.name + " (" + str(len(rows)) + " rows)")


def main() -> int:
    rng = random.Random(SEED)
    write(HERE / "before_manual.csv", manual(rng))
    write(HERE / "after_automated.csv", automated(rng))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
